#pod template used for testing

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: status
  name: status-http
spec:
  containers:
  - name: toaster
    image: example/toaster 
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 256Mi
    env:
    - name: URL
      value: https://google.com
  imagePullSecrets:
  - name: regcred
  restartPolicy: Never
